language = "Español"

[login]
groups_page_title = '.*Grupos \| Facebook'

[publish]
text_pending_posts = '\d+ (publicación|publicaciones)'
button_write_something = "Escribe algo.*"
button_start_discussion = "Iniciar conversación.*"
tab_discussion = "Conversación.*"
loader_posting = "Publicando"
button_post = "Publicar"
textarea_create_post = "Crea una publicación.*"
textarea_write_something = "Escribe algo"
button_photo_video = "Foto/video"
