"""Create users table

Revision ID: 4671c78364f9
Revises:
Create Date: 2025-06-06 18:02:21.794007

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4671c78364f9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("jwt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("previous_jwt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "role", sa.Enum("super_admin", "user", name="roleenum"), nullable=False
        ),
        sa.Column("is_disabled", sa.Boolean(), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_machine_id"), "users", ["machine_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_machine_id"), table_name="users")
    op.drop_table("users")

    # Drop enum type
    role_enum = sa.Enum("super_admin", "user", name="roleenum")
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
