"""remove role add admin table

Revision ID: afbde32ddf99
Revises: b3eae62bfb36
Create Date: 2025-12-06 09:03:05.965094

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "afbde32ddf99"
down_revision: Union[str, None] = "b3eae62bfb36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("admin_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("admin_id"),
        sa.UniqueConstraint("admin_id"),
    )
    op.drop_column("users", "password")
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            postgresql.ENUM("super_admin", "user", name="roleenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table("admin")
    # ### end Alembic commands ###
