"""Add user password column

Revision ID: b3eae62bfb36
Revises: 4671c78364f9
Create Date: 2025-12-03 15:31:52.971323

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from app.config import settings
from app.security import get_password_hash

# revision identifiers, used by Alembic.
revision: str = "b3eae62bfb36"
down_revision: Union[str, None] = "4671c78364f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# SUPER_ADMIN_ID = settings.super_admin_id
# SUPER_ADMIN_PASSWORD = settings.super_admin_password


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("users", "is_disabled", existing_type=sa.BOOLEAN(), nullable=False)

    # Set super admin password
    hashed_password = get_password_hash("")  # SUPER_ADMIN_PASSWORD
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            UPDATE users
            SET password = :password
            WHERE user_id = :user_id
            AND role = 'super_admin'
        """),
        {"password": hashed_password, "user_id": ""},  # SUPER_ADMIN_ID
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_disabled", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("users", "password")
    # ### end Alembic commands ###
