language = "English"

[login]
groups_page_title = '.*Groups \| Facebook'

[publish]
text_pending_posts = '\d+ posts?'
button_write_something = "Write something.*"
button_start_discussion = "Start discussion.*"
tab_discussion = "Discussion.*"
loader_posting = "Posting.*"
button_post = "Post"
textarea_create_post = "Create a public post"
textarea_write_something = "Write something"
button_photo_video = "Photo/video"
