name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true

permissions:
  contents: write

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pipx install uv
          uv sync
  
      - name: Build executable with Nuitka
        run: |
          uv run nuitka --assume-yes-for-downloads --onefile --include-data-files=styles.tcss=styles.tcss --include-data-dir=locales_fb=locales_fb --linux-icon=./assets/autofbpost.ico --playwright-include-browser=none --output-filename=autofbpost main.py
  
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          body: "Latest version"
          files: autofbpost
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pipx install uv
          uv sync

      - name: Build with Nuitka
        run: |
          uv run nuitka --assume-yes-for-downloads --onefile --include-data-files=styles.tcss=styles.tcss --include-data-dir=locales_fb=locales_fb --windows-icon-from-ico=./assets/autofbpost.ico --playwright-include-browser=none --output-filename=autofbpost main.py
        shell: cmd

      - name: Upload Windows binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          body: "Release"
          files: autofbpost.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
